version: "3.9"

services:
  backend:
    build: .
    container_name: case_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code 
      - db_data:/code/data
    environment:
      - PYTHONUNBUFFERED=1
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: bash /code/start.sh
    
volumes:
  db_data: