name: CI/CD Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2 server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@18.219.241.6 << 'EOF'
            cd ~/app
            
            if [ -d "CommonAssessmentTool" ]; then
              echo "Updating existing repository..."
              cd CommonAssessmentTool
              git fetch --all
              git reset --hard origin/main
            else
              echo "Cloning repository..."
              git clone https://github.com/CaseManagementAI-5500/CommonAssessmentTool.git
              cd CommonAssessmentTool
            fi
            
            if [ ! -f "docker-compose.yml" ] || [ ! -f "Dockerfile" ]; then
              echo "ERROR: Required files are missing!"
              ls -la
              exit 1
            fi
            
            echo "Building and starting containers..."
            docker-compose down
            docker-compose up --build -d
            
            echo "Deployment completed successfully!"
          EOF
